name: Issue opened

on:
  issues:
    types: [opened]

jobs:
  check-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Check issue title
        if: github.event.issue.title == 'build request from airtable'
        run: |
          build_output=$(echo "Build is test")
          echo "${build_output}" | gh issue comment ${github.event.issue.number}
